services:
  backend:
    #build: ./backend
    image: zzz6839/animefan-monitor2-backend:main
    ports:
      - "58000:58000"
    volumes:
      - backend_data:/app/data
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai

  frontend:
    #build: ./frontend
    image: zzz6839/animefan-monitor2-frontend:main
    ports:
      - "53000:53000"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=http://backend:58000
      - TZ=Asia/Shanghai
      - VITE_TIMEZONE=Asia/Shanghai
volumes:
  backend_data:
