services:
  backend:
    #build:
    #  context: ./backend
    #  dockerfile: Dockerfile
    image: zzz6839/animefan-monitor-backend:latest
    ports:
      - "28000:8000"
    volumes:
      - anime_data:/data
    environment:
      - DEBUG=true
      - BACKEND_CORS_ORIGINS=["http://localhost:15173","http://localhost:5173","http://localhost:3000"]
    restart: unless-stopped
    networks:
      - anime_network

  frontend:
    #build:
    #  context: ./frontend
    #  dockerfile: Dockerfile
    image: zzz6839/animefan-monitor-frontend:latest
    ports:
      - "15173:80"
    environment:
      - API_URL=http://backend:8000
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - anime_network

volumes:
  anime_data:

networks:
  anime_network:
    driver: bridge
